### ISSUE TITLE
Feature request: Model that utilizes embeddings.

### ISSUE THREAD

**Issue by netrome** [Demborg/LSTM_sentiment#19]
We have now shown that we can overfit the existing data quite well. However for better generalization I think we need an embedding layer between the input and the sequential parts of our models (no matter if they are GRU:s, LSTM:s, CNN-LSTMs or whatever. Therefore I propose that we create a model with embeddings to compare to some of our existing models. I think it is okay if we let the model learn the embeddings for now. However using pre-trained embeddings may also work.

**Comment by Demborg** [comment]
Okay, yeah sure that sounds resonable. I have started looking a bit at the documentation about embeddings in pytorch and if I understand it correctly torch.nn.Embedding  has no learnable parameters? Have  tried looking at some of the tutorials etc but I  can't really wrap my head around how it is supposed to be used, do any of you have some insight?

**Comment by Demborg** [comment]
and an other thought about how we handle output from embedded models, I think the most resonable approach would be to broadcast the score at each word to each character in that word and return output on the same shape as for the other models, that would help keep everything comparable right? If we go that path though where do we handle broadcasting? in the model itself? any ideas?

**Comment by Demborg** [comment]
Oh silly me, read the docs more properly now and found the learnable parameters

**Comment by netrome** [comment]
I think we can use embeddings in two different ways. Right now our models are agnostic regarding if the input is a character, embedding or a word and I prefer to keep it that way. From this point we can include embeddings in models which I would like to try out, and apply these models on the raw data. Another approach is to write a new dataset where the embeddings are applied directly in the data-loading step. This might require quite heavy pre-trained embeddings but might give good results. Both of these approaches can of course be used together. Personally I would like to start with the model that operates on the raw data and learns its own embeddings.

Speaking of data processing it would be nice to write a separate dataset class that filters out some information, like removing special characters and making everything lower case. The filtered information could be kept by adding some separate indicator dimensions for these (such as lowercase/uppercase).

**Comment by Demborg** [comment]
#20
